-- DDL
-- CREATE
-- ALTER
-- DROP

CREATE DATABASE Usuário
   Id INT PRIMARY KEY NOT NULL,
   Nome VARCHAR(50) NOT NULL,
   Email VARCHAR(50) NOT NULL,
   Telefone NCHAR(50) NOT NULL,
)

CREATE DATABASE Anuncio
   Id INT PRIMARY KEY NOT NULL,
   Tipo VARCHAR(50) NOT NULL,
   Descricao VARCHAR(50) NOT NULL,
   Preco FLOAT(50) NOT NULL,
   Contato VARCHAR(50) NOT NULL,
   FK_Usuário INT NOT NULL,

)
