-- DDL
-- CREAT
-- ALTER
-- DROP

CREATE DATABASE db_E commerce

USE db_E Commerce

CREATE TABLE Usuarios(
    Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(50) NOT NULL,
	Telefone NCHAR(50) NOT NULL,
	Endereco VARCHAR(50) NOT NULL,
)

CREATE DATABASE Pedidos(
    Id INT PRIMARY KEY IDENTITY NOT NULL,
	Tipo VARCHAR(50) NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	Preco FLOAT(50) NOT NULL,
	FK_Usuario INT NOT NULL,

)

CREATE DATABASE Carrinho(
    Id INT PRIMARY KEY NOT NULL,
	QUANTIDADE VARCHAR(50) NOT NULL,
	FRETE FLOAT(50) NOT NULL,
	Preco FLOAT(50) NOT NULL,
	FK_Usuarios INT NOT NULL,
	FK_Pedidos INT NOT NULL,

)