-- DDL
-- CREATE
-- ALTER
-- DROP

CREATE DATABASE marketplace

USE marketplace

CREATE TABLE Usuários(
    Id INT PRIMARY KEY NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Senha VARCHAR(50) NOT NULL,
	Endereco VARCHAR(50) NULL,
)

CREATE TABLE Categorias(
    Id INT PRIMARY KEY NOT NULL,
	Descricao VARCHAR(50)

)

CREATE TABLE Produtos(
    Id INT PRIMARY KEY IDENTITY NOT NULL,
	NomeProduto VARCHAR(50) NOT NULL,
	Descricao VARCHAR(150) NOT NULL,
	Preco FLOAT NULL,
	FK_CRIADOR INT NOT NULL,
	FK_Categoria INT NOT NULL,
	FOREIGN KEY (FK_CRIADOR) REFERENCES Usuários (Id),
	FOREIGN KEY (FK_CRIADOR) REFERENCES Usuários (Id)

)

CREATE TABLE Compras(
    FK_Comprador INT NOT NULL,
	FK_Produto INT NOT NULL,
	FOREIGN KEY (FK_Comprador) REFERENCES Usuários (Id)
	FOREIGN KEY (FK_Produto) REFERENCES Produtos (Id)

)