--DDL
--CREAT
--ALTER
--DROP

CREATE DATABASE Rede Social

USE Rede Social

CREATE TABLE Usuario
   Id INT PRIMARY KEY NOT NULL,
   Nome VARCHAR(50) NOT NULL,
   Email VARCHAR(50) NOT NULL,
   Telefone NCHAR(50) NOT NULL,
   Senha VARCHAR(50) NOT NULL,

)

CREATE TABLE Postagem
   Id INT PRIMARY KEY NOT NULL,
   Titulo VARCHAR(50) NOT NULL,
   Descricao VARCHAR(150) NOT NULL,
   Inserir Fotos VARCHAR(300) NOT NULL,
   Inserir Videos VARCHAR(500) NOT NULL,
   FK_Usuario INT NOT NULL,
   FK_Tema INT NOT NULL,
 )

 CREATE TABLE Tema
   Id INT PRIMARY KEY IDENTITY NOT NULL,
   Assunto VARCHAR(50) NOT NULL

)

CREATE TABLE Grupo
    Id INT PRIMARY KEY NOT NULL,
	Postagem VARCHAR(100) NOT NULL,
	FK_Usuario INT NOT NULL
)